modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory
credits="Thanks IAmAnAvacado for the great idea!" #optional
[[mods]] #mandatory
modId="betterbeds" #mandatory
version="1.2" #mandatory
displayName="The Better Beds Mod" #mandatory
authors="Eleksploded" #optional
description='''
BEDS!!
'''