
[General]
	#Enables/Disables hardcore mode, bedrock instead of beds
	hardcore = false
	#Block Blacklist for Bedification ["mod:block","mod:block"]
	blacklist = ["minecraft:end_portal_frame","minecraft:stone"]

